all_projects/__init__.py
from flask import Flask
app = Flask(__name__, instance_relative_config=False)
app.config['SECRET_KEY'] = 'mysecretkey'
from all_projects.core.views import core
app.register_blueprint(core)

all_projects/core/views.py
from flask import Blueprint, render_template, url_for, request


core = Blueprint('core', __name__)

@core.route('/')
def index():
    return render_template('index.html')

@core.route('/info')
def info():
    return render_template('info.html')

all_projects/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <title>Experiment</title>
  </head>
  <style>

  .bg {
      /* The image used */
      background-image: url("https://images.pexels.com/photos/531880/pexels-photo-531880.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940");

      }


   .footer {
  position: float;
  left: 0;
  bottom: 0;
  width: 100%;
  background-color: #b6c0cc;
  text-align: center;
  padding-bottom: 0.5%;
  }
  </style>
  <body>
    <div class="bg">
    <nav class="navbar navbar-expand-md navbar-light bg-light border sticky-top">
  <a class="navbar-brand" style="color: #3c6afc; vertical-align: inherit;" href="/">Abhinav Kumar  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto mt-2">
      <li class = 'nav-item'>
        <a class = 'nav-link' id = "index-nav-link" href="{{url_for('core.index')}}">Home</a>
      </li>
      <li class = 'nav-item'>
        <a class = 'nav-link' id = "index-nav-link" href="{{url_for('core.info')}}">About Me</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto mt-2">
      <li class = 'nav-item'>
        <a class = 'nav-link'  href="https://github.com/Abhinavk910" target="_blank">GitHub</a>
      </li>
      <li class = 'nav-item'>
        <a class = 'nav-link'  href="https://www.kaggle.com/abhinavkum" target="_blank">Kaggle</a>
      </li>
      <li class = 'nav-item'>
        <a class = 'nav-link'  href="https://public.tableau.com/profile/abhik910#!/" target="_blank">Tableau</a>
      </li>
      <li class = 'nav-item'>
        <a class = 'nav-link'  href="https://www.linkedin.com/in/Abhinavk910/" target="_blank">LinkedIn</a>
      </li>
    </ul>
  </div>
</nav>
      <div class="container">
      {% block content %}


      {% endblock %}
    </div>

    <!--
    <div class="footer">
      <div class="text-center pt-2 ">
        <h6 class="text-uppercase font-weight-bold" >contact</h6>
        <p>-
           +91-7982585375
           <br>
           New Delhi, India
         </p>
      </div>
    </div> -->
    <!-- <nav class="navbar navbar-light bg-light border  navbar-fixed-bottom">
      <div class="text-center">
        <h6 class="text-uppercase font-weight-bold" >contact</h6>
        <p>
           +91-7982585375
           <br>
           New Delhi, India
         </p>
      </div>
    </nav> -->
    <footer class="footer">
          <div class="container">
            <span class="text-muted font-weight-bold">CONTACT</span>
            <span class = text-Center> <br> +91-7982585375 <br>
            New Delhi, India</span>
          </div>
        </footer>

  </body>
</html>

all_projects/templates/index.html
  {% extends 'base.html' %}

{% block content %}

<section>

<div class="jumbotron card card-image pt-5 " style="background-image: url({{url_for('static', filename ='logo/gradient.jpg')}}); height: 100%;">
  <div class="text-white text-center py-5 px-4">
    <div>
      <h2 class="card-title h1-responsive pt-3 mb-5 font-bold"><strong>DATA SCIENCE & AUTOMATION</strong></h2>
      <p class="mx-5 mb-5 ">
        I am a passionate data scientist and am particularly enthusiastic about the interface between data science and automation.
      </p>
    </div>
  </div>
</div>
    <!--Grid row-->
    <div class="row mx-1">

        <!--Grid column-->
        <div class="col-md-6 mb-4">
            <div class="card card-image" style="background-image: url({{url_for('static', filename ='logo/sudoku.jpg')}}); height:100%;">
              <!-- background-image: url({{ url_for('static', filename='img/home.jpg') }}) -->
                <div class=" text-center d-flex align-items-center rgba-black-strong py-5 px-4">
                    <div>
                        <h6 class="green-text"><i class="fas fa-chart-pie"></i><strong> Latest Project</strong></h6>
                        <h3 class="card-title py-3 font-weight-bold"><strong>Sudoku Solver</strong></h3>
                        <p class="pb-3 bg-info">
                          Used opencv for finding grid and number and tensorflow for number recognition.
                        </p>
                        <a class="btn btn-secondary btn-rounded" href="https://github.com/Abhinavk910/OpenCV/tree/master/project_sudoku_solver" target="_blank">
                          <i class="far fa-clone left"></i> View project</a>
                    </div>
                </div>
            </div>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">
            <div class="card card-image"
            style="background-image: url({{url_for('static', filename ='logo/tensorflow.png')}}); height:100%;">
                <div class="text-center d-flex align-items-center rgba-black-strong py-5 px-4">
                    <div>
                        <h6 class="green-text"><i class="far fa-eye"></i><strong> Latest Course</strong></h6>
                        <h3 class="card-title py-3 font-weight-bold"><strong>Tensorflow In Practice</strong></h3>
                        <p class="pb-3 bg-info">Discovered the tools used to build scalable AI-powered algorithms in TensorFlow, a popular open-source machine learning framework.</p>
                        <a class="btn btn-secondary btn-rounded" href="https://www.coursera.org/account/accomplishments/specialization/LMJL97VTLECX" target="_blank">
                          <i class="far fa-clone left">
                          </i>
                          View Certificate
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <!--Grid column-->

    </div>
    <!--Grid row-->

</section>
<!--Projects section v.4-->
{% endblock %}